name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  paths:
     - Azure_terraform/Data Resources
jobs:
    #build:
    #    name: Call Azure Pipeline
    #    runs-on: ubuntu-latest
    #    steps:
    #    - name: Azure Pipelines Action
    #      uses: Azure/pipelines@v1
    #      with:
    #        azure-devops-project-url: https://dev.azure.com/prairiesunflower/prairesunflower
    #        azure-pipeline-name: 'krynn1.Personal'
    #        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        uses: hashicorp/setup-terraform@v2
      - name: terraform init
        run: terraform init
      - name: terraform plan -out:outfile.txt
        run: terraform plan -out:outfile.txt
      - name: terraform apply
        run: terraform apply "outfile.txt"