name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - masters
jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - uses: Azure/login@v1
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Check out repository
        uses: actions/checkout@v3
      #- name: moving directories
      #  run: |
      #    cd Azure_terraform
      #    cd Data Resources
      - name: terraform install
        uses: hashicorp/setup-terraform@v2
      - name: terraform init
        run: terraform init
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
            #client-id: ${{ secrets.clientId }}
            #tenant-id: ${{ secrets.tenantId }}
            #subscription-id: ${{ secrets.subscriptionId }}
            #client_secret: $${{ secrets.clientSecret }} 
        working-directory: Azure_terraform/Data resources
      - name: terraform plan -out:outfile.txt
        run: terraform plan -out:outfile.txt
        working-directory: Azure_terraform/Data resources
      - name: terraform apply
        run: terraform apply "outfile.txt"
        working-directory: Azure_terraform/Data resources